In [1]:
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import List, Optional
from pypdf import PdfReader
from dotenv import load_dotenv

# Load OPENAI_API_KEY from a local .env file (see .env.example) - never hard-code a key
load_dotenv()

client = OpenAI()

class PaperData(BaseModel):
    title: str = Field(description="The title of the paper")
    abstract_summary: List[str] = Field(description="One sentence summary of the abstract")
    intro_backgrounds_summary: str = Field(description="One sentence summary of the intro and backgrounds sections")
    methods_summary: str = Field(description="One sentence summary of the methods section")
    results_summary: str = Field(description="One sentence summary of the results section")
    discussion_summary: str = Field(description="One sentence summary of the discussion section")
    

def load_pdf_text(file_path):
    '''Loads text from a PDF file.'''
    # creating a pdf reader object
    reader = PdfReader(file_path)

    # extracting text from page
    text = "\n\n".join([page.extract_text() for page in reader.pages])
    
    return text

In [2]:
import os, urllib.request

def download_pdf(url, dest):
    """Download a PDF to `dest` if it is not already there (cross-platform; no wget)."""
    if os.path.exists(dest):
        print(f"Already present: {dest}")
        return
    os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as r, open(dest, "wb") as f:
        f.write(r.read())
    print(f"Downloaded: {dest}")

download_pdf("https://arxiv.org/pdf/2510.26493", "../assets/paper.pdf")

Already present: ../assets/paper.pdf

In [3]:
paper_raw_text = load_pdf_text("../assets/paper.pdf")

response = client.responses.parse(
    model="gpt-5.6-luna",
    input=f"extract the information from the paper: {paper_raw_text}",
    text_format=PaperData
)

print(response)

ParsedResponse(id='resp_054f79410b570b11006ab0fc66a3bc87d289a5dbfd2700c36b', created_at=1789983846.0, error=None, incomplete_details=None, instructions=None, metadata={}, model='gpt-5.6-luna', object='response', output=[ResponseReasoningItem(id='rs_054f79410b570b11006ab0fc67880c87d29c84b580c8972a9c', summary=[], type='reasoning', content=[], encrypted_content='gAAAAABqsPxqHHynEPXjuColmZx79i1Nwtu_IkgBM3RB03j87Og99qCYaEgobfLJM67asIwg0SAWIBSPNGtLKnwtNchUf42YFpsz4_v8xs9isb0PV9qA_f4KLmBP2mOFBWeaWM5YEyIo2FqiL56qeMfw4xvbOpFqOHZ-UHeZcqxEvTtAn53xR2udDDmM5NlrwPxI3ijlo-2f7OA13QVH08A1K86RczRbk-mvaA3V0zhGqcXwpQQZEK0y0QVqFhkM7Y1vh-cHCA9eCrpezgqW8N8y7NrTJjk_DxZLlcpEFSS-zzZHXaMNOBjr5xGq_CieXQZdMagq_75V5-ASj8r9qwuhm5E4POSIHkFQMqJS_UqnKOj3h5y7RC5SXzvDbY7NRPSxDtEC9VvT7M9A4wggTk7nNCd0pLsBEGQ9gbnvkGWovjifhWwYX58AxW-TrQOVzB0mjrKwQ_BWkKooemWaqYBZRppMPlkNM4Ojzg3bEpwSyEJRVXwB2WI-Ab98kT0nHEGduOb9cDHefHrDn5GDZO5YKCErkeaJfwdF5NwhYe8sS9lG0Nm6DGI6S0RpVp4krXJXEdeq3uKUQ-2kyhSM_2gwxrIEtVLSU_FSEbrbUez-ijpdMuTrxpaDBTOEbouZoSJkJAv7vM6dgLpuaWfry5pos1GDYS45aDIQSLoZcDZE13KV701OLyUoslxtTjuNLuyAA8Hvug496I3mPGZjBDyrM80TZcVNx2FVafkmXWuC2rWNAWpWeRgMpzX19_iWTtuAN2s4XppuISly9wlQLVgKpvqzizHNTHe_NDI85GuK3KpA1Gctu17K_jkUqNyunSm-lnDY7EdmD1X7Qn7diwSzqHMQahNB-N_yRf9txq_ovP1K5-khNjnEvD_KA_RCtNTCULLvUHqdvQXHwb7h-x_fi_jwUEKEKHRPCeFGQAbOf0p5INmOQzmjGGoUkkzJ80huBOV8EP9YAK6TJBIlP65svx4uLyddMosyVSlwsVekQG7nMTpvH7_FwHsDRiTlk7Y58lxNFIL993xTIaoCOCZu0qa7d_6JmIH0zre1i4-McnaiU4M3IuLt3oEMTkOCoJpLooe4LuC6W9x5wOlXAvymXP7mQMUE--pUj8avjDll5TS8RelTQawXGTarDlWn5FmO0veR5ID70-9KMTd-UZV_ZtI27XMjx-ECRs1-TioQ4W-wGcMmhLhNswCL67TU_tbh_Z60zpcmBkp2CRql5tkR-cztYAmsF_iiQZHt44HvC6Y_eCevz3dhpFR91J7s9cwmbK0FZAam_4LpIZ7fsgyoC7EOvDcGgWNsKwcaJA70NVxutYl1am3o6xlN-RZquS6txdbE-NY6yKB2R4HvTb3LKPoUno75QV79YaLSRPipgeO8skTUtrMeBWIURiO11mqbypYyot9XZxSq_5yItgoM067G5ffOvv4wwWAXcybJNIrLR9PTuZ3WeN1W1lUcE_0bBK449VJqlFo64utFS9CsMejd07SfcOhumqI1sBZ8WKjkL0pt6_qehrrIv7qs7OEBGFUXbzni3qjOLAWfxYPs7MSJL4HTtjgxAeLX3k4ROtt3pTVbw0o=', status=None), ParsedResponseOutputMessage(id='msg_054f79410b570b11006ab0fc68096087d292f90f35ccd2f15f', content=[ParsedResponseOutputText(annotations=[], text='{"title":"Context Engineering 2.0: The Context of Context Engineering","abstract_summary":["The paper presents context engineering as the systematic design, collection, storage, management, and use of contextual information to reduce the gap between human intentions and machine understanding, tracing its evolution from early human–computer interaction to future human-level and superhuman AI systems."],"intro_backgrounds_summary":"The introduction situates context engineering within the longer history of ubiquitous computing, context-aware systems, HCI, prompting, retrieval, tool use, and agent memory, arguing that increasing machine intelligence progressively reduces the human effort required to translate high-entropy intentions into machine-readable context.","methods_summary":"The authors develop a conceptual and theoretical framework that formally defines entities, interactions, context, and context engineering, compares four evolutionary stages, reviews historical practices, and organizes design considerations around context collection and storage, management, and usage.","results_summary":"The paper characterizes Context Engineering 1.0 as structured, sensor-driven, human-prepared input and Context Engineering 2.0 as agent-centered processing of natural-language and multimodal context, while outlining future 3.0 and 4.0 stages involving human-level understanding and proactive or superhuman context construction.","discussion_summary":"The discussion identifies challenges involving multimodal collection, lifelong storage, context overload, long-context efficiency, relevance selection, system stability, evaluation, privacy, and proactive need inference, and proposes a future semantic operating system that actively organizes, updates, explains, and manages context over time."}', type='output_text', logprobs=[], parsed=PaperData(title='Context Engineering 2.0: The Context of Context Engineering', abstract_summary=['The paper presents context engineering as the systematic design, collection, storage, management, and use of contextual information to reduce the gap between human intentions and machine understanding, tracing its evolution from early human–computer interaction to future human-level and superhuman AI systems.'], intro_backgrounds_summary='The introduction situates context engineering within the longer history of ubiquitous computing, context-aware systems, HCI, prompting, retrieval, tool use, and agent memory, arguing that increasing machine intelligence progressively reduces the human effort required to translate high-entropy intentions into machine-readable context.', methods_summary='The authors develop a conceptual and theoretical framework that formally defines entities, interactions, context, and context engineering, compares four evolutionary stages, reviews historical practices, and organizes design considerations around context collection and storage, management, and usage.', results_summary='The paper characterizes Context Engineering 1.0 as structured, sensor-driven, human-prepared input and Context Engineering 2.0 as agent-centered processing of natural-language and multimodal context, while outlining future 3.0 and 4.0 stages involving human-level understanding and proactive or superhuman context construction.', discussion_summary='The discussion identifies challenges involving multimodal collection, lifelong storage, context overload, long-context efficiency, relevance selection, system stability, evaluation, privacy, and proactive need inference, and proposes a future semantic operating system that actively organizes, updates, explains, and manages context over time.'))], role='assistant', status='completed', type='message', phase='final_answer')], parallel_tool_calls=True, temperature=1.0, tool_choice='auto', tools=[], top_p=0.98, background=False, completed_at=1789983850.0, conversation=None, max_output_tokens=None, max_tool_calls=None, moderation=None, previous_response_id=None, prompt=None, prompt_cache_diagnostics=None, prompt_cache_key=None, prompt_cache_options=None, prompt_cache_retention='24h', reasoning=Reasoning(context='all_turns', effort='medium', generate_summary=None, mode='standard', summary=None), safety_identifier=None, service_tier='default', status='completed', text=ResponseTextConfig(format=ResponseFormatTextJSONSchemaConfig(name='PaperData', schema_={'properties': {'title': {'description': 'The title of the paper', 'title': 'Title', 'type': 'string'}, 'abstract_summary': {'description': 'One sentence summary of the abstract', 'items': {'type': 'string'}, 'title': 'Abstract Summary', 'type': 'array'}, 'intro_backgrounds_summary': {'description': 'One sentence summary of the intro and backgrounds sections', 'title': 'Intro Backgrounds Summary', 'type': 'string'}, 'methods_summary': {'description': 'One sentence summary of the methods section', 'title': 'Methods Summary', 'type': 'string'}, 'results_summary': {'description': 'One sentence summary of the results section', 'title': 'Results Summary', 'type': 'string'}, 'discussion_summary': {'description': 'One sentence summary of the discussion section', 'title': 'Discussion Summary', 'type': 'string'}}, 'required': ['title', 'abstract_summary', 'intro_backgrounds_summary', 'methods_summary', 'results_summary', 'discussion_summary'], 'title': 'PaperData', 'type': 'object', 'additionalProperties': False}, type='json_schema', description=None, strict=True), verbosity='medium'), top_logprobs=0, truncation='disabled', usage=ResponseUsage(input_tokens=27742, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=27739), output_tokens=370, output_tokens_details=OutputTokensDetails(reasoning_tokens=56), total_tokens=28112), user=None, billing={'payer': 'developer'}, frequency_penalty=0.0, presence_penalty=0.0, store=True, tool_usage={'image_gen': {'input_tokens': 0, 'input_tokens_details': {'image_tokens': 0, 'text_tokens': 0}, 'output_tokens': 0, 'output_tokens_details': {'image_tokens': 0, 'text_tokens': 0}, 'total_tokens': 0}, 'web_search': {'num_requests': 0}})

In [4]:
response.output_parsed

PaperData(title='Context Engineering 2.0: The Context of Context Engineering', abstract_summary=['The paper presents context engineering as the systematic design, collection, storage, management, and use of contextual information to reduce the gap between human intentions and machine understanding, tracing its evolution from early human–computer interaction to future human-level and superhuman AI systems.'], intro_backgrounds_summary='The introduction situates context engineering within the longer history of ubiquitous computing, context-aware systems, HCI, prompting, retrieval, tool use, and agent memory, arguing that increasing machine intelligence progressively reduces the human effort required to translate high-entropy intentions into machine-readable context.', methods_summary='The authors develop a conceptual and theoretical framework that formally defines entities, interactions, context, and context engineering, compares four evolutionary stages, reviews historical practices, and organizes design considerations around context collection and storage, management, and usage.', results_summary='The paper characterizes Context Engineering 1.0 as structured, sensor-driven, human-prepared input and Context Engineering 2.0 as agent-centered processing of natural-language and multimodal context, while outlining future 3.0 and 4.0 stages involving human-level understanding and proactive or superhuman context construction.', discussion_summary='The discussion identifies challenges involving multimodal collection, lifelong storage, context overload, long-context efficiency, relevance selection, system stability, evaluation, privacy, and proactive need inference, and proposes a future semantic operating system that actively organizes, updates, explains, and manages context over time.')

In [5]:
from IPython.display import Markdown, display

md = f"""
# {response.output_parsed.title}

## Abstract Summary
{'; '.join(response.output_parsed.abstract_summary)}

## Introduction & Backgrounds Summary
{response.output_parsed.intro_backgrounds_summary}

## Methods Summary
{response.output_parsed.methods_summary}

## Results Summary
{response.output_parsed.results_summary}

## Discussion Summary
{response.output_parsed.discussion_summary}
"""

display(Markdown(md))

# Context Engineering 2.0: The Context of Context Engineering

## Abstract Summary
The paper presents context engineering as the systematic design, collection, storage, management, and use of contextual information to reduce the gap between human intentions and machine understanding, tracing its evolution from early human–computer interaction to future human-level and superhuman AI systems.

## Introduction & Backgrounds Summary
The introduction situates context engineering within the longer history of ubiquitous computing, context-aware systems, HCI, prompting, retrieval, tool use, and agent memory, arguing that increasing machine intelligence progressively reduces the human effort required to translate high-entropy intentions into machine-readable context.

## Methods Summary
The authors develop a conceptual and theoretical framework that formally defines entities, interactions, context, and context engineering, compares four evolutionary stages, reviews historical practices, and organizes design considerations around context collection and storage, management, and usage.

## Results Summary
The paper characterizes Context Engineering 1.0 as structured, sensor-driven, human-prepared input and Context Engineering 2.0 as agent-centered processing of natural-language and multimodal context, while outlining future 3.0 and 4.0 stages involving human-level understanding and proactive or superhuman context construction.

## Discussion Summary
The discussion identifies challenges involving multimodal collection, lifelong storage, context overload, long-context efficiency, relevance selection, system stability, evaluation, privacy, and proactive need inference, and proposes a future semantic operating system that actively organizes, updates, explains, and manages context over time.

In [6]:
import pandas as pd
import os

def upsert_paper_to_csv(paper_data, csv_path="papers_database.csv", key_column="title"):
    """
    Inserts or updates a paper's data in a CSV file database. If the file does not exist,
    it creates it. If the file exists, it updates the entry if the key exists, or appends 
    the new paper if not.

    Parameters:
        paper_data: an object with attributes corresponding to extracted fields
        csv_path: output file path for CSV
        key_column: column name to use as unique identifier (default: "title")
    """
    # Prepare data dictionary, flattening abstract_summary if it's a list
    paper_dict = {
        "title": getattr(paper_data, "title", ""),
        "abstract_summary": "; ".join(paper_data.abstract_summary) if isinstance(getattr(paper_data, "abstract_summary", ""), list) else getattr(paper_data, "abstract_summary", ""),
        "intro_backgrounds_summary": getattr(paper_data, "intro_backgrounds_summary", ""),
        "methods_summary": getattr(paper_data, "methods_summary", ""),
        "results_summary": getattr(paper_data, "results_summary", ""),
        "discussion_summary": getattr(paper_data, "discussion_summary", ""),
    }

    # If CSV exists, load and update if key matches; otherwise create new
    if os.path.isfile(csv_path):
        df = pd.read_csv(csv_path)
        # Check if key (e.g., title) already in db
        if paper_dict[key_column] in df[key_column].values:
            # Update existing entry
            df.loc[df[key_column] == paper_dict[key_column], list(paper_dict.keys())] = list(paper_dict.values())
            updated = True
        else:
            # Append if not found
            df = pd.concat([df, pd.DataFrame([paper_dict])], ignore_index=True)
            updated = False
    else:
        # Create new dataframe
        df = pd.DataFrame([paper_dict])
        updated = False

    df.to_csv(csv_path, index=False)
    if updated:
        print(f"Updated entry in '{csv_path}' for {key_column}='{paper_dict[key_column]}'")
    else:
        print(f"Added new entry to '{csv_path}' for {key_column}='{paper_dict[key_column]}'")

# Example usage:
upsert_paper_to_csv(response.output_parsed)

Added new entry to 'papers_database.csv' for title='Context Engineering 2.0: The Context of Context Engineering'

In [7]:
import pandas as pd

df = pd.read_csv("papers_database.csv")

df

,title,abstract_summary,intro_backgrounds_summary,methods_summary,results_summary,discussion_summary
0,Context Engineering 2.0: The Context of Contex...,The paper presents context engineering as the ...,The introduction situates context engineering ...,The authors develop a conceptual and theoretic...,The paper characterizes Context Engineering 1....,The discussion identifies challenges involving...

In [8]:
download_pdf("https://arxiv.org/pdf/1301.3781", "../assets/paper3.pdf")

Already present: ../assets/paper3.pdf

In [9]:
def extract_paper_data_workflow(paper_path: str):
    paper_raw_text = load_pdf_text(paper_path)

    response = client.responses.parse(
        model="gpt-5.6-luna",
        input=f"extract the information from the paper: {paper_raw_text}",
        text_format=PaperData
    )
    
    output_parsed = response.output_parsed

    print(output_parsed)
    
    upsert_paper_to_csv(output_parsed)
    
    return output_parsed

extract_paper_data_workflow("../assets/paper3.pdf")

title='Efficient Estimation of Word Representations in Vector Space' abstract_summary=['The paper introduces the CBOW and Skip-gram architectures for efficiently learning high-quality word vectors from massive text corpora, demonstrating improved syntactic and semantic relationship performance at substantially lower computational cost.'] intro_backgrounds_summary='The paper motivates distributed word representations as a scalable alternative to atomic word indices and reviews neural language-model approaches, emphasizing the need for methods capable of training high-dimensional vectors on billions of words while preserving linear semantic and syntactic relationships.' methods_summary='The authors compare feedforward and recurrent neural language models with two simpler log-linear architectures—Continuous Bag-of-Words, which predicts a target word from surrounding context, and Continuous Skip-gram, which predicts surrounding words from a target word—using hierarchical softmax, stochastic gradient training, and large-scale distributed optimization.' results_summary='On semantic-syntactic analogy benchmarks, Skip-gram and CBOW substantially outperform earlier models, with large-scale distributed training achieving 65.6% total accuracy for 1000-dimensional Skip-gram vectors and showing that high-quality vectors can be trained on billions of words within a few days.' discussion_summary='The authors conclude that simple CBOW and Skip-gram models provide an efficient foundation for learning highly accurate word representations at unprecedented scale, support meaningful vector arithmetic, and have broad potential for NLP applications including translation, retrieval, question answering, and knowledge-base construction.'
Added new entry to 'papers_database.csv' for title='Efficient Estimation of Word Representations in Vector Space'

PaperData(title='Efficient Estimation of Word Representations in Vector Space', abstract_summary=['The paper introduces the CBOW and Skip-gram architectures for efficiently learning high-quality word vectors from massive text corpora, demonstrating improved syntactic and semantic relationship performance at substantially lower computational cost.'], intro_backgrounds_summary='The paper motivates distributed word representations as a scalable alternative to atomic word indices and reviews neural language-model approaches, emphasizing the need for methods capable of training high-dimensional vectors on billions of words while preserving linear semantic and syntactic relationships.', methods_summary='The authors compare feedforward and recurrent neural language models with two simpler log-linear architectures—Continuous Bag-of-Words, which predicts a target word from surrounding context, and Continuous Skip-gram, which predicts surrounding words from a target word—using hierarchical softmax, stochastic gradient training, and large-scale distributed optimization.', results_summary='On semantic-syntactic analogy benchmarks, Skip-gram and CBOW substantially outperform earlier models, with large-scale distributed training achieving 65.6% total accuracy for 1000-dimensional Skip-gram vectors and showing that high-quality vectors can be trained on billions of words within a few days.', discussion_summary='The authors conclude that simple CBOW and Skip-gram models provide an efficient foundation for learning highly accurate word representations at unprecedented scale, support meaningful vector arithmetic, and have broad potential for NLP applications including translation, retrieval, question answering, and knowledge-base construction.')

In [10]:
import pandas as pd


df = pd.read_csv("papers_database.csv")
df

,title,abstract_summary,intro_backgrounds_summary,methods_summary,results_summary,discussion_summary
0,Context Engineering 2.0: The Context of Contex...,The paper presents context engineering as the ...,The introduction situates context engineering ...,The authors develop a conceptual and theoretic...,The paper characterizes Context Engineering 1....,The discussion identifies challenges involving...
1,Efficient Estimation of Word Representations i...,The paper introduces the CBOW and Skip-gram ar...,The paper motivates distributed word represent...,The authors compare feedforward and recurrent ...,"On semantic-syntactic analogy benchmarks, Skip...",The authors conclude that simple CBOW and Skip...

In [11]:
tool_schema = {
    "type": "function",
    "name": "extract_paper_data_workflow",
    "description": "Extracts data from a paper",
    "parameters": {
        "type": "object",
        "properties": {
            "paper_path": {
                "type": "string",
                "description": "The path to the paper"
            }
        },
        "required": ["paper_path"],
    }
}

tool_schema

{'type': 'function',
 'name': 'extract_paper_data_workflow',
 'description': 'Extracts data from a paper',
 'parameters': {'type': 'object',
  'properties': {'paper_path': {'type': 'string',
    'description': 'The path to the paper'}},
  'required': ['paper_path']}}

In [12]:
download_pdf("https://arxiv.org/pdf/2412.14161", "./test_agent_paper.pdf")

Already present: ./test_agent_paper.pdf

In [13]:
response = client.responses.create(
    model="gpt-5.6-luna",
    instructions="You are an extraction agent, users will give you paths to files for pdfs\
                  and you will extract the data from the paper using the:\
                  extract_paper_data function.",
    tools=[tool_schema],
    input="Extract data from this paper: ./test_agent_paper.pdf"
)

response.output_text

''

In [14]:
response.output

[ResponseReasoningItem(id='rs_0ea6da665f023cd5006ab0fc70f39087d2a539c2c3ccca620b', summary=[], type='reasoning', content=[], encrypted_content='gAAAAABqsPxxqyt6JQ8VuWZLde5pbY2YqUEuiKrGmRVnvf0qZD37PGtQet2mabPadLya2LsfROYmEW4YPU9J0tTe09-9gA0iw1sfDFgVcVAnShzK5enyn0roGHyXpRhUrZGdME83t6vizC5UnP8AVjFI2dgaI-nIyW2lhAGyLl9sEtBkoxeqKwuqnQJ-teXgd07lg-zDnEHOyfmIsXRQveGYaDCoG8e6Higk6zsk6N46IcFJsSozrG5enEChC_GFRGty_gevcioR_O3CA0Rd1yNY5MdiTujGzybxgbDehkkBwDCuw9c5wXOnHRTgyqnPaf2Vaf_PbaNxFjSAzMGOIaGtRwQtfTjNdyjZGmRjRH5Tt5CRILZfik5kKcrpEPDkbeH-eQdh_6eQowDmj_ci7Ke59NkIcUNsjjReZXjtIYE8Kcpp5KyeLMs7mEkipPpgJNjahq35ZdCqDwNJXhL0YYGeghN1BWGvdHhdvfRLDMMdNVd2IOc1n1ZNjdDwJ-rH0X3-3CNE0Bm7A--szPq9lQtA9y1j8pJAlwbyXNmgBTdqOJ_HMya3eEP-OdVLqPMa4NlxgWvV04pAraIxDZ1OpMvLm9wx5NuDpgtLXJADSUJgiF7MBF2KgndAuiM4YLRoYr6ozivhUCKtTmq5vs8oldAAtXsc0rp4DOgPmvzLBw6bik3MarEOuomso1kSeGYZOvYSng2anABKRZqQ8reW5Abq-NYO3gXXLVuT3cVWI6fb2t5DZZosUjO5bWSHMvdYZeE2c0BGTg6HkxQlcFGCMU4X4IXKS5mo_skaCKEkdwhAeA3ZdM2aIPWWM57yXCwIadIPejkuWreFEAJi8x1uN2K6vJ9aYb3VaWnDmFxBbwN9yhiopwUboqLdeFtG5z1t0uBdnc_MtzXHdnSxBtQ9_HMLesQ6BuiIfAf_DcEvftfR3fCS-ey65Ql2NhArp1ZhxEce9w2MMdPRUytIxDwHVcbLRzafyS4ZRxjsH79kXV7c8V3x1EPK_PsdGlKEpjs7fzwk7oKgy6zY50aBfGDudQYFldg61-NnD5W-kMVvs7H_LdrsHHD5mt0vXnZKSC502l_gPh7sZWf-TtZGbl8OnA_GGbbG0kG9sjosXDDCEkDX3ItWMpgFXD24PH5KBMSLaoz36UeGAiVHJ6OLwS2s_aKgVQeorYYo9hcfpz2p33zvYTDQxOPyhXPvxWtGObZPzhZO0fwpIytZ', status=None),
 ResponseFunctionToolCall(arguments='{"paper_path":"./test_agent_paper.pdf"}', call_id='call_pMngzh5wsXAZFSD49aZk1mAs', name='extract_paper_data_workflow', type='function_call', id='fc_0ea6da665f023cd5006ab0fc71140887d2a9ef435e6365b372', async_=None, caller=None, namespace=None, status='completed')]